# 1. 데이터 불러오기

In [2]:
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
import warnings

In [4]:
plt.style.use('seaborn')
plt.rcParams['figure.figsize']=[16,9]
plt.rcParams['figure.dpi']=300
warnings.simplefilter(action='ignore',category=FutureWarning)

## 1) 야후 파이낸스 데이터 불러오기

In [7]:
import pandas as pd
import yfinance as yf

In [10]:
df_yahoo = yf.download('AAPL',start='2019-01-01',end='2020-12-31',progress=False)

- AAPL은 애플 티커(종목기호) 인데 다른 종목기호 넣으면 다른 종목을 얻을 수 있음

In [11]:
df_yahoo

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-12-31,39.632500,39.840000,39.119999,39.435001,38.233894,140014000
2019-01-02,38.722500,39.712502,38.557499,39.480000,38.277523,148158800
2019-01-03,35.994999,36.430000,35.500000,35.547501,34.464802,365248800
2019-01-04,36.132500,37.137501,35.950001,37.064999,35.936081,234428400
2019-01-07,37.174999,37.207500,36.474998,36.982498,35.856091,219111200
...,...,...,...,...,...,...
2020-12-23,132.160004,132.429993,130.779999,130.960007,129.992004,88223700
2020-12-24,131.320007,133.460007,131.100006,131.970001,130.994507,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,135.679642,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,133.873077,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,132.731567,96452100

In [12]:
yf.download(['AAPL','MU'],start='2019-01-01',end='2020-12-31',progress=False)

             Adj Close                  Close                   High  \
                  AAPL         MU        AAPL         MU        AAPL
Date
2018-12-31   38.233898  31.651962   39.435001  31.730000   39.840000
2019-01-02   38.277531  32.669453   39.480000  32.750000   39.712502
2019-01-03   34.464802  30.923758   35.547501  31.000000   36.430000
2019-01-04   35.936077  32.619576   37.064999  32.700001   37.137501
2019-01-07   35.856083  33.916378   36.982498  34.000000   37.207500
...                ...        ...         ...        ...         ...
2020-12-23  129.991989  69.777962  130.960007  69.949997  132.429993
2020-12-24  130.994537  70.406418  131.970001  70.580002  133.460007
2020-12-28  135.679626  70.486221  136.690002  70.660004  137.339996
2020-12-29  133.873077  70.037315  134.869995  70.209999  138.789993
2020-12-30  132.731598  71.743111  133.720001  71.919998  135.990005

                              Low                   Open             \
                   MU        AAPL         MU        AAPL         MU
Date
2018-12-31  32.400002   39.119999  31.459999   39.632500  31.990000
2019-01-02  33.080002   38.557499  30.750000   38.722500  31.000000
2019-01-03  32.150002   35.500000  30.860001   35.994999  31.820000
2019-01-04  33.040001   35.950001  31.549999   36.132500  31.660000
2019-01-07  34.450001   36.474998  33.310001   37.174999  33.700001
...               ...         ...        ...         ...        ...
2020-12-23  71.059998  130.779999  69.889999  132.160004  70.470001
2020-12-24  70.639999  131.100006  69.760002  131.320007  70.309998
2020-12-28  72.110001  133.509995  70.470001  133.990005  71.790001
2020-12-29  71.400002  134.339996  69.139999  138.050003  71.000000
2020-12-30  72.650002  133.399994  70.370003  135.580002  70.419998

               Volume
                 AAPL        MU
Date
2018-12-31  140014000  21392100
2019-01-02  148158800  26004300
2019-01-03  365248800  29145500
2019-01-04  234428400  28557300
2019-01-07  219111200  44841500
...               ...       ...
2020-12-23   88223700   8524000
2020-12-24   54930100   4848500
2020-12-28  124486200   8345200
2020-12-29  121047300   9403400
2020-12-30   96452100  11620300

[505 rows x 12 columns]

In [15]:
yf.download(['AAPL'],start='2019-01-01',end='2020-12-31',progress=False,auto_adjust=True,actions='inline')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2018-12-31,38.425377,38.626558,37.928486,38.233894,140014000,0.0,0.0
2019-01-02,37.543099,38.502947,37.383124,38.277527,148158800,0.0,0.0
2019-01-03,34.898670,35.320422,34.418748,34.464802,365248800,0.0,0.0
2019-01-04,35.031980,36.006371,34.855040,35.936077,234428400,0.0,0.0
2019-01-07,36.042732,36.074244,35.364052,35.856094,219111200,0.0,0.0
...,...,...,...,...,...,...,...
2020-12-23,131.183116,131.451109,129.813312,129.991989,88223700,0.0,0.0
2020-12-24,130.349333,132.473514,130.130958,130.994522,54930100,0.0,0.0
2020-12-28,132.999602,136.324831,132.523139,135.679642,124486200,0.0,0.0
2020-12-29,137.029580,137.764100,133.346996,133.873077,121047300,0.0,0.0
2020-12-30,134.577835,134.984808,132.413941,132.731583,96452100,0.0,0.0

In [39]:
yf.Ticker('MSFT').info

{'zip': '98052-6399',
 'sector': 'Technology',
 'fullTimeEmployees': 181000,
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. Its Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. It has collaborations with Dynatrace, Inc., Morgan Stanley, Micro Focus, WPP plc, ACI Worldwide, Inc., and iCIMS, Inc., as well as strategic relationships with Avaya Holdings Corp. and wejo Limited. Microsoft Corporation was founded in 1975 and is based in Redmond, Washington.',
 'city': 'Redmond',
 'phone': '425 882 8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'https://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'industry': 'Software—Infrastructure',
 'ebitdaMargins': 0.49123,
 'profitMargins': 0.38498002,
 'grossMargins': 0.68825996,
 'operatingCashflow': 83909001216,
 'revenueGrowth': 0.201,
 'operatingMargins': 0.42523998,
 'ebitda': 90829996032,
 'targetLowPrice': 306.55,
 'recommendationKey': 'buy',
 'grossProfits': 115856000000,
 'freeCashflow': 46479876096,
 'targetMedianPrice': 370,
 'currentPrice': 310.88,
 'earningsGrowth': 0.222,
 'currentRatio': 2.247,
 'returnOnAssets': 0.15248999,
 'numberOfAnalystOpinions': 47,
 'targetMeanPrice': 370.13,
 'debtToEquity': 50.217,
 'returnOnEquity': 0.49051,
 'targetHighPrice': 425,
 'totalCash': 125348003840,
 'totalDebt': 80353001472,
 'totalRevenue': 184902991872,
 'totalCashPerShare': 16.72,
 'financialCurrency': 'USD',
 'revenuePerShare': 24.585,
 'quickRatio': 2.05,
 'recommendationMean': 1.7,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 12.527,
 'beta3Year': None,
 'enterpriseToEbitda': 25.501,
 '52WeekChange': 0.2440176,
 'morningStarRiskRating': None,
 'forwardEps': 10.75,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7496869888,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 21.335,
 'sharesShort': 36442967,
 'sharesPercentSharesOut': 0.0049,
 'fundFamily': None,
 'lastFiscalYearEnd': 1625011200,
 'heldPercentInstitutions': 0.71876997,
 'netIncomeToCommon': 71184998400,
 'trailingEps': 9.389,
 'lastDividendValue': 0.62,
 'SandP52WeekChange': 0.10911167,
 'priceToBook': 14.5713625,
 'heldPercentInsiders': 0.00059,
 'nextFiscalYearEnd': 1688083200,
 'yield': None,
 'mostRecentQuarter': 1640908800,
 'shortRatio': 1.04,
 'sharesShortPreviousMonthDate': 1644883200,
 'floatShares': 7489894342,
 'beta': 0.908333,
 'enterpriseValue': 2316293111808,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'legalType': None,
 'lastDividendDate': 1652832000,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.214,
 'priceToSalesTrailing12Months': 12.604592,
 'dateShortInterest': 1647302400,
 'pegRatio': 1.94,
 'ytdReturn': None,
 'forwardPE': 28.91907,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0049,
 'sharesShortPriorMonth': 35348757,
 'impliedSharesOutstanding': 0,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 314.97,
 'regularMarketOpen': 313.27,
 'twoHundredDayAverage': 304.15994,
 'trailingAnnualDividendYield': 0.007492777,
 'payoutRatio': 0.2449,
 'volume24Hr': None,
 'regularMarketDayHigh': 314.865,
 'navPrice': None,
 'averageDailyVolume10Day': 26882740,
 'regularMarketPreviousClose': 314.97,
 'fiftyDayAverage': 298.353,
 'trailingAnnualDividendRate': 2.36,
 'open': 313.27,
 'toCurrency': None,
 'averageVolume10days': 26882740,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 2.48,
 'exDividendDate': 1652832000,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 309.87,
 'currency': 'USD',
 'trailingPE': 33.111088,
 'regularMarketVolume': 22978920,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 2330626883584,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 37902426,
 'dayLow': 309.87,
 'ask': 0,
 'askSize': 900,
 'volume': 22978920,
 'fiftyTwoWeekHigh': 349.67,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.32,
 'fiftyTwoWeekLow': 238.07,
 'bid': 0,
 'tradeable': False,
 'dividendYield': 0.008,
 'bidSize': 1000,
 'dayHigh': 314.865,
 'regularMarketPrice': 310.88,
 'preMarketPrice': 307.29,
 'logo_url': 'https://logo.clearbit.com/microsoft.com',
 'trailingPegRatio': 2.1672}

- 종목에 대한 요약 설명, 직원 수 등등 광범위 한 정보 포함된 딕셔너리 나옴

## 2) 퀀들로 데이터 불러오기

먼저 https://www.quandl.com 에서 아이디를 만들어 개별 api key를 받아야한다.

In [52]:
import pandas as pd
import quandl

In [53]:
quandl_key = '개별 API KEY'
quandl.ApiConfig.api_key = quandl_key

In [59]:
df_quaundl = quandl.get(dataset='WIKI/AAPL',start_date='2019-01-13',end_date='2020-12-13')

In [58]:
quandl.get(dataset='LBMA/GOLD',start_date='2019-01-13',end_date='2020-12-13')

            USD (AM)  USD (PM)  GBP (AM)  GBP (PM)  EURO (AM)  EURO (PM)
Date
2019-01-14   1293.70   1292.75   1007.02   1006.15    1129.27    1127.41
2019-01-15   1289.35   1294.40   1002.99   1008.60    1127.67    1130.53
2019-01-16   1290.50   1292.30   1002.46   1002.95    1130.99    1133.86
2019-01-17   1294.00   1290.70   1004.92    999.39    1135.87    1133.49
2019-01-18   1285.05   1284.20    993.34    994.74    1126.86    1128.94
...              ...       ...       ...       ...        ...        ...
2020-12-07   1832.80   1859.95   1380.46   1397.01    1513.34    1531.11
2020-12-08   1864.50   1868.15   1396.14   1401.49    1538.77    1540.48
2020-12-09   1859.80   1841.75   1382.39   1372.29    1533.22    1521.65
2020-12-10   1834.20   1844.35   1377.48   1385.29    1515.23    1517.53
2020-12-11   1833.65   1842.00   1386.97   1394.21    1510.93    1519.65

[487 rows x 6 columns]

- 데이터 검색해서 클릭 후 USAGE 탭에 가면 python, R 등에서 불러오는 방법 사용 가능

### 3. Intrinio에서 데이터 불러오기

먼저 https://intrinio.com 에 등록하여 개별 api key를 먼저 받아야 한다.

In [62]:
import intrinio_sdk
import pandas as pd

In [65]:
# key는 개인 api key 중 sandbox key 사용
intrinio_sdk.ApiClient().configuration.api_key['api_key'] = '개별 API KEY'
security_api = intrinio_sdk.SecurityApi()

In [66]:
r = security_api.get_security_stock_prices(identifier='AAPL',
                                           start_date='2020-01-01',end_date='2021-12-30',frequency='daily',page_size=1000)

In [67]:
response_list = [x.to_dict() for x in r.stock_prices]
df_intrinio = pd.DataFrame(response_list).sort_values('date')
df_intrinio.set_index('date',inplace=True)

In [68]:
df_intrinio

,intraperiod,frequency,open,high,low,close,volume,adj_open,adj_high,adj_low,adj_close,adj_volume,factor,split_ratio,dividend,change,percent_change,fifty_two_week_high,fifty_two_week_low
date,,,,,,,,,,,,,,,,,,,
2020-01-02,False,daily,296.24,300.6000,295.190,300.35,33911864.0,73.082514,74.158127,72.823478,74.096452,135647456.0,1.000000,1.0,0.00,1.65,0.0228,74.16,34.51
2020-01-03,False,daily,297.15,300.5800,296.500,297.43,36633878.0,73.307011,74.153193,73.146656,73.376087,146535512.0,1.000000,1.0,0.00,-0.72,-0.0097,74.16,34.95
2020-01-06,False,daily,293.79,299.9600,292.750,299.80,29644644.0,72.478098,74.000239,72.221530,73.960767,118578576.0,1.000000,1.0,0.00,0.58,0.0080,74.16,35.46
2020-01-07,False,daily,299.84,300.9000,297.480,298.39,27877655.0,73.970635,74.232138,73.388422,73.612920,111510620.0,1.000000,1.0,0.00,-0.35,-0.0047,74.23,36.10
2020-01-08,False,daily,297.16,304.4399,297.156,303.19,33090946.0,73.309478,75.105432,73.308491,74.797081,132363784.0,1.000000,1.0,0.00,1.18,0.0161,75.11,36.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03,False,daily,145.81,148.0450,145.180,147.36,64786618.0,145.591870,147.823526,144.962812,147.139551,64786618.0,1.000000,1.0,0.00,1.84,0.0126,149.78,102.44
2021-08-04,False,daily,147.27,147.7900,146.280,146.95,56368271.0,147.049686,147.568908,146.061167,146.730165,56368271.0,1.000000,1.0,0.00,-0.41,-0.0028,149.78,102.44
2021-08-05,False,daily,146.98,147.8400,146.170,147.06,46397674.0,146.760120,147.618833,145.951331,146.840000,46397674.0,1.000000,1.0,0.00,0.11,0.0007,149.78,102.44
2021-08-06,False,daily,146.35,147.1100,145.630,146.14,54126813.0,146.350000,147.110000,145.630000,146.140000,54126813.0,0.998504,1.0,0.22,-0.70,-0.0048,149.78,102.44
2021-08-09,False,daily,146.20,146.7000,145.520,146.09,48815544.0,146.200000,146.700000,145.520000,146.090000,48815544.0,1.000000,1.0,0.00,-0.05,-0.0003,149.78,102.44